In [66]:
import pandas as pd

# Load your data
df = pd.read_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/cluster_contig.csv', sep=',')  # Adjust separator as needed

# Combine 'placeholder' and 'Provisional-Name'
df['contig_key'] = df['sample'].astype(str) + '_' + df['contig'].astype(str)

# Save the updated data
df.to_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/1cluster_contig.csv', sep=',', index=False)

In [ ]:
SEZ_ON_OWOG_R001_S75_687911
SEZONOWIFRR031_LIV_S71_663085
SEZONOWIFRR032_LIV_S72_666406
SEZONOWIFRR039_LIV_S79_666401
SEZONOWIFRR040_LIV_S80_666396
SEZONOWIFRR069_LUNG_S60_673526
SEZONOWOGR001_LIV_S47_666398
SEZONOWOGR010_LIV_S56_666407

In [229]:
from ete3 import NCBITaxa
import pandas as pd

# Load the data
lca = pd.read_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_stats_lca.tsv', sep='\t')

# Initialize NCBI Taxa instance
ncbi = NCBITaxa()

# Function to retrieve taxonomic ranks
def get_taxonomy_ranks(tax_id, ranks=('phylum', 'family')):
    try:
        lineage = ncbi.get_lineage(tax_id)
        names = ncbi.get_taxid_translator(lineage)
        ranks_info = ncbi.get_rank(lineage)
        result = {rank: names[tax] for tax, rank in ranks_info.items() if rank in ranks}
        return [result.get(rank, 'NA') for rank in ranks]
    except Exception as e:
        return ['NA'] * len(ranks)

# Add phylum and family columns
lca[['phylum', 'family']] = lca['tax_id'].apply(lambda x: pd.Series(get_taxonomy_ranks(int(x))))

# Save the updated file
output_path = '/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_stats_lca_updated.tsv'
lca.to_csv(output_path, sep='\t', index=False)

/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 59451 was translated into 3371016
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 143291 was translated into 132908
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 85948 was translated into 147567
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 90247 was translated into 3371155
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 228257 was translated into 3082113
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2991674 was translated into 3383038
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 7604 was translated into 133437
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2052317 was translated into 3107663
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1914757 was translated into 1768011
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2789583 was translated into 2841044
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2991676 was translated into 3383035
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 39086 was translated into 3370998
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2650730 was translated into 261694
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1906744 was translated into 1796644
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2817377 was translated into 2817376
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 139420 was translated into 2498619
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2811023 was translated into 1903157
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 436010 was translated into 1759441
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 77222 was translated into 3370833
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 381198 was translated into 8845
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1114980 was translated into 2144
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 9413 was translated into 3371112
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 59452 was translated into 3371021
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 302711 was translated into 225400
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 686832 was translated into 76867
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))

ModuleNotFoundError: No module named 'ace_tools'

In [263]:
import pandas as pd

# Define the path to your input and output TSV files
input_tsv = '/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_stats_lca_updated.tsv'
output_tsv = '/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_stats_lca_annotated.tsv'

# Read the TSV into a DataFrame
df = pd.read_csv(input_tsv, sep='\t')

# Check if 'phylum' column exists
if 'phylum' not in df.columns:
    raise ValueError("The 'phylum' column is not present in the TSV file.")

# Create a new column 'is_chordata' based on the 'phylum' column
df['chordata'] = df['phylum'].astype(str).str.strip().str.lower() == 'chordata'

# Optionally, handle NaN values by setting them to False
df['chordata'] = df['chordata'].fillna(False)

# Write the updated DataFrame to a new TSV file
df.to_csv(output_tsv, sep='\t', index=False)

print(f"Replacements done. Updated file saved as {output_tsv}")

Replacements done. Updated file saved as /Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_stats_lca_annotated.tsv

In [112]:
import pandas as pd

# Define the path to your input TSV file
input_tsv = '/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Cluster_contigs/contig_stats_filtered_lca_updated.tsv'
output_tsv = '/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Cluster_contigs/1contig_stats_filtered_lca_updated.tsv'

# Read the TSV into a DataFrame
df = pd.read_csv(input_tsv, sep="\t")

# Define the mapping of old names to new names
replacement_map = {
    'NE_S70_670946': 'NE_water1_S70_670946',
    'NE_S82_663084': 'NE_water2_S82_663084',
    'NTC_S71_670947': 'NTC_water3_S71_670947',
    "SSP_ERCC_S72_670948":"SSP_water5_ERCC_S72_670948",
    "SSP_ERCC_S83_666426":"SSP_water4_ERCC_S83_666426"
}

# Apply replacements to specified columns, if they exist
for col in ['sample', 'contig_name']:
    if col in df.columns:
        for old, new in replacement_map.items():
            df[col] = df[col].astype(str).str.replace(old, new, regex=False)

# Write the updated DataFrame to a new TSV file
df.to_csv(output_tsv, sep="\t", index=False)
print(f"Replacements done. Updated file saved as {output_tsv}")

Replacements done. Updated file saved as /Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Cluster_contigs/1contig_stats_filtered_lca_updated.tsv

In [5]:
import pandas as pd

In [7]:
lca = pd.read_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_stats_lca_annotated.tsv', sep='\t')
lca['blasted'] = True
lca.rename({'taxid': 'taxid_blast', 'taxon_group': 'taxon_group_blast'}, axis = 1, inplace = True)
lca['taxon_group_blast'] = lca.apply(lambda x: 'chordata' if x.chordata else x.taxon_group_blast, axis = 1)

read_counts = pd.read_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_stats.tsv', sep='\t')

In [8]:
lca

,sample,contig_name,contig_length,read_count,nr,nt_or_nr,bitscore,align_length,taxon_group_blast,tax_id,...,sci_name,com_names,lca_taxid,lca_taxid.1,lca_name,common_nr,phylum,family,chordata,blasted
0,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1006_length_47...,479,6,True,nr,52.4,32,chordata,10029,...,Cricetulus griseus,XP_035304239.1 mitogen-activated protein kinas...,NaN,NaN,NaN,True,Chordata,Cricetidae,True,True
1,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1008_length_47...,479,8,True,nr,188.0,166,chordata,109678,...,Phodopus roborovskii,CAH7434577.1 Gm8113 [Phodopus roborovskii],NaN,NaN,NaN,True,Chordata,Cricetidae,True,True
2,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1014_length_47...,478,8,True,nr,51.6,40,chordata,10089,...,Mus caroli,XP_021035475.1 centromere protein P isoform X2...,NaN,NaN,NaN,True,Chordata,Muridae,True,True
3,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1019_length_47...,477,183,True,nr,254.0,158,chordata,61156,...,Arvicanthis niloticus,XP_034344067.1 LOW QUALITY PROTEIN: uncharacte...,NaN,NaN,NaN,True,Chordata,Muridae,True,True
4,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1021_length_47...,477,13,True,nr,136.0,111,Viruses,11855,...,Mason-Pfizer monkey virus,"2D4N_A Chain A, DU [Mason-Pfizer monkey virus]",NaN,NaN,NaN,True,Artverviricota,Retroviridae,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,SEZONOWOGR004_LIV_S50_666375,SEZONOWOGR004_LIV_S50_666375_NODE_5444_length_...,391,16,True,nr,174.0,93,chordata,35658,...,Mastomys coucha,XP_031217140.1 inter-alpha-trypsin inhibitor h...,35658.0,35658.0,Mastomys coucha,True,Chordata,Muridae,True,True
1048571,SEZONOWOGR004_LIV_S50_666375,SEZONOWOGR004_LIV_S50_666375_NODE_5451_length_...,391,9,True,nr,47.4,31,chordata,10090,...,Mus musculus,BAB27170.1 unnamed protein product [Mus musculus],10090.0,10090.0,Mus musculus,True,Chordata,Muridae,True,True
1048572,SEZONOWOGR004_LIV_S50_666375,SEZONOWOGR004_LIV_S50_666375_NODE_5452_length_...,391,11,True,nr,56.6,47,chordata,10129,...,Apodemus sylvaticus,XP_052046283.1 ral guanine nucleotide dissocia...,NaN,NaN,NaN,True,Chordata,Muridae,True,True
1048573,SEZONOWOGR004_LIV_S50_666375,SEZONOWOGR004_LIV_S50_666375_NODE_5454_length_...,391,14,True,nr,115.0,77,chordata,564181,...,Peromyscus californicus insignis,XP_052618045.1 uncharacterized protein LOC1281...,NaN,NaN,NaN,True,Chordata,Cricetidae,True,True
1048574,SEZONOWOGR004_LIV_S50_666375,SEZONOWOGR004_LIV_S50_666375_NODE_5463_length_...,391,7,True,nr,179.0,118,chordata,35658,...,Mastomys coucha,XP_031207626.1 LOW QUALITY PROTEIN: sperm moti...,NaN,NaN,NaN,True,Chordata,Muridae,True,True

In [9]:
cluster_to_virus = pd.read_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/clusters_to_virus.csv')

In [10]:
cluster_to_contigs = pd.read_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/1cluster_contig.csv')
cluster_to_contigs.rename({'contig': 'contig_name'}, axis = 1, inplace=True)

In [11]:
curated_viruses = (cluster_to_contigs
                       .merge(cluster_to_virus, on='cluster', how = 'right', )
                       .merge(read_counts, on=['sample', 'contig_name'], how = 'left',))
curated_viruses['curated'] = True
curated_viruses['rdrp'] = curated_viruses['segment'].str.lower().str.contains('rdrp')
curated_viruses['rdrp'] |= (curated_viruses['segment'] == 'genome')

curated_viruses.rename({'submission_taxid': 'taxid_curated'}, axis = 1, inplace = True)

In [12]:
curated_viruses['rdrp'].sum()

469

In [19]:
contig_calls = lca.merge(curated_viruses,
                         on = ['sample', 'contig_name', 'contig_length', 'read_count'],
                         how = 'outer')
contig_calls.fillna({'blasted': False,
                     'curated': False,
                     'taxon_group_blast': 'Dark',
                     'rdrp': False}, inplace=True)

In [21]:
contig_calls['taxon_group'] = contig_calls.apply(lambda x: ('Viruses' if x['curated'] else x['taxon_group_blast']), axis = 1)
contig_calls['taxid'] = contig_calls.apply(lambda x: x['taxid_curated'] if x['curated'] else x['tax_id'], axis = 1)

In [22]:
contig_calls

,sample,contig_name,contig_length,read_count,nr,nt_or_nr,bitscore,align_length,taxon_group_blast,tax_id,...,cluster,taxid_curated,poly_group,name,provisional_name,segment,curated,rdrp,taxon_group,taxid
0,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1006_length_47...,479,6,True,nr,52.4,32.0,chordata,10029.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,chordata,10029.0
1,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1008_length_47...,479,8,True,nr,188.0,166.0,chordata,109678.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,chordata,109678.0
2,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1014_length_47...,478,8,True,nr,51.6,40.0,chordata,10089.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,chordata,10089.0
3,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1019_length_47...,477,183,True,nr,254.0,158.0,chordata,61156.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,chordata,61156.0
4,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1021_length_47...,477,13,True,nr,136.0,111.0,Viruses,11855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,Viruses,11855.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1054503,SEZOOWISUGOAT002_S27_657721,SEZOOWISUGOAT002_S27_657721_NODE_244_length_96...,969,87,NaN,NaN,NaN,NaN,Dark,NaN,...,55739.0,693066.0,100.0,Bovine rhinitis B virus,NaN,RNA1,True,False,Viruses,693066.0
1054504,SEZONOWOWISR001_LIV_S62_666415,SEZONOWOWISR001_LIV_S62_666415_NODE_1_length_3...,3723,741,NaN,NaN,NaN,NaN,Dark,NaN,...,3019.0,1431460.0,111.0,Hunnivirus A,NaN,RNA1,True,False,Viruses,1431460.0
1054505,SEZONOWOWISR001_LIV_S62_666415,SEZONOWOWISR001_LIV_S62_666415_NODE_10_length_...,977,136,NaN,NaN,NaN,NaN,Dark,NaN,...,54725.0,1431460.0,111.0,Hunnivirus A,NaN,RNA1,True,False,Viruses,1431460.0
1054506,SEZONOWOWISR001_LIV_S62_666415,SEZONOWOWISR001_LIV_S62_666415_NODE_15_length_...,918,92,NaN,NaN,NaN,NaN,Dark,NaN,...,62628.0,1431460.0,111.0,Hunnivirus A,NaN,RNA1,True,False,Viruses,1431460.0
1054507,SEZOOWOGCHICKEN001_S35_655749,SEZOOWOGCHICKEN001_S35_655749_NODE_914_length_...,621,12,NaN,NaN,NaN,NaN,Dark,NaN,...,161013.0,990667.0,118.0,Picornavirus turkey/TRK22/USA/2010,NaN,RNA1,True,False,Viruses,990667.0

In [9]:
import pandas as pd

# Replace 'final_contig_count.csv' with the path to your CSV file
df = pd.read_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_stats_lca_annotated.tsv', sep='\t')

# 1) Number of rows
num_rows = len(df)
print("Number of rows:", num_rows)

# 2) Sum of the 'count' column
#   Make sure the column in your CSV is actually named 'count'
#   If it's named something else, adjust accordingly.
total_count = df['read_count'].sum()
print("Sum of 'count' column:", total_count)

Number of rows: 1048575
Sum of 'count' column: 144228028

In [23]:
contig_calls.groupby('taxon_group')['read_count'].sum()

taxon_group
Ambiguous      201297
Archaea        251902
Bacteria     77399808
Eukaryota    15568414
Metazoa       4373277
Viruses      62533121
chordata     29165141
Name: read_count, dtype: int64

In [ ]:
Ambiguous      201297
Archaea        251902
Bacteria     77399808
Eukaryota    15568414
Metazoa       4373277
Viruses      62533121
chordata     29165141
Dark           491160

In [27]:
contig_calls[contig_calls['curated']].groupby(['taxon_group_blast'])['read_count'].sum()

taxon_group_blast
Ambiguous        1360
Bacteria        68248
Dark           491160
Eukaryota       25446
Metazoa           404
Viruses      42996271
chordata     11640819
Name: read_count, dtype: int64

In [284]:
contig_calls[contig_calls['taxon_group_blast'] == 'Dark'].groupby(['rdrp'])['read_count'].sum()

rdrp
False    453313
True      37847
Name: read_count, dtype: int64

In [289]:
contig_calls.to_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_calls.tsv',
                    sep='\t', index = False)

In [29]:
import pandas as pd

# Assume contig_calls DataFrame is already loaded
# Example: contig_calls = pd.read_csv('your_input_file.csv')

# Write the complete DataFrame to a TSV file
contig_calls.to_csv(
    '/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_calls.tsv',
    sep='\t',
    index=False
)

# List of taxon groups to split by
taxon_groups = ["Ambiguous", "Bacteria", "Dark", "Eukaryota", "Metazoa", "Viruses", "chordata"]

# Output directory (ensure this directory exists)
output_directory = '/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/'

# Loop over each taxon group, filter the DataFrame, and write to a CSV file
for group in taxon_groups:
    group_df = contig_calls[contig_calls['taxon_group_blast'] == group]
    output_file = f"{output_directory}{group}_contig_calls.csv"
    group_df.to_csv(output_file, index=False)
    print(f"Written {len(group_df)} rows for group '{group}' to {output_file}")

print("Finished writing all CSV files.")

Written 625 rows for group 'Ambiguous' to /Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/Ambiguous_contig_calls.csv
Written 557279 rows for group 'Bacteria' to /Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/Bacteria_contig_calls.csv
Written 465 rows for group 'Dark' to /Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/Dark_contig_calls.csv
Written 57417 rows for group 'Eukaryota' to /Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/Eukaryota_contig_calls.csv
Written 9723 rows for group 'Metazoa' to /Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/Metazoa_contig_calls.csv
Written 45488 rows for group 'Viruses' to /Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/Viruses_contig_calls.csv
Written 380617 rows for group 'chordata' to /Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/chordata_contig_calls.csv
Finished writing all CSV files.

In [290]:
sample_table = pd.read_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/correct_Idseq_metatda.csv')

sample_table['water'] = sample_table['water'].fillna(False).astype(bool)
print(sample_table['water'].dtype)  # should now be bool

bool

In [294]:
# Mark as water if sample starts with one of these prefixes
sample_table['water'] = sample_table['sample'].str.startswith(('SSP_', 'NTC_', 'NE_'))

# Keep only relevant columns
sample_table = sample_table[['sample',
                             'total_reads',
                             'nonhost_reads',
                             'total_ercc_reads',
                             'compression_ratio',
                             'water']]

# Compute extra columns
sample_table['input_conc'] = sample_table.eval('(total_reads - total_ercc_reads) / total_ercc_reads')
sample_table['nonhost_frac'] = sample_table.eval('nonhost_reads * compression_ratio / total_reads')

# Count how many are marked as water
n_water = sample_table['water'].sum()
n_water

7

In [296]:
def sum_over(df, category):
    return df[[category, 'sample', 'read_count']].groupby([category, 'sample']).sum().reset_index()

In [298]:
read_counts = sum_over(contig_calls, 'poly_group')
read_counts

      poly_group                           sample  read_count
0            1.0           AIMGLDOG001_S59_657733          12
1            2.0           AIMGLDOG001_S59_657733          44
2            3.0           AIAMAPIG002_S64_657714         234
3            4.0           AIAMAPIG002_S64_657714          16
4            5.0    SEZONOWIFRR031_LIV_S71_663085          31
...          ...                              ...         ...
1992       403.0   SEZONOWIFRR063_LUNG_S81_666397       37358
1993       403.0   SEZONOWIFRR070_LUNG_S61_673529         613
1994       403.0   SEZONOWIFRR071_LUNG_S62_673527       40532
1995       403.0    SEZONOWOGR082_LUNG_S58_666410          27
1996       403.0  SEZONOWOWISR087_LUNG_S68_666423        7128

[1997 rows x 3 columns]

In [300]:
def decontam(read_counts, category, fdr):
    background_levels = (read_counts.merge(sample_table[sample_table['water']],
                                          on='sample', validate='many_to_one')
                         .eval('r_per_ercc = read_count*compression_ratio/total_ercc_reads')
                         [['r_per_ercc', category]]
                         .groupby(category).sum()/n_water)
    
    df = read_counts.merge(sample_table, on = 'sample', how = 'left')
    df = df[~df['water']]
    df = df.merge(background_levels, on=category, how = 'left').fillna({'r_per_ercc': 0}).eval(
    'background_reads = total_ercc_reads*r_per_ercc/compression_ratio')
    df['is_contam'] = df['read_count'] < df['background_reads']/fdr
    
    return df[['sample', category, 'is_contam', 'read_count']]

In [302]:
viral_df = sum_over(contig_calls[contig_calls['curated']], 'poly_group')
viral_df = decontam(viral_df, 'poly_group', 0.00000000001)

In [304]:

viral_df

                               sample  poly_group  is_contam  read_count
0              AIMGLDOG001_S59_657733         1.0      False          12
1              AIMGLDOG001_S59_657733         2.0      False          44
2              AIAMAPIG002_S64_657714         3.0      False         234
3              AIAMAPIG002_S64_657714         4.0      False          16
4       SEZONOWIFRR031_LIV_S71_663085         5.0      False          31
...                               ...         ...        ...         ...
1985   SEZONOWIFRR063_LUNG_S81_666397       403.0      False       37358
1986   SEZONOWIFRR070_LUNG_S61_673529       403.0      False         613
1987   SEZONOWIFRR071_LUNG_S62_673527       403.0      False       40532
1988    SEZONOWOGR082_LUNG_S58_666410       403.0      False          27
1989  SEZONOWOWISR087_LUNG_S68_666423       403.0      False        7128

[1990 rows x 4 columns]

In [306]:
viral_df.groupby('is_contam')['read_count'].sum()

is_contam
False    55222928
True          277
Name: read_count, dtype: int64

In [308]:
# Write contam and decontam files
viral_decontam = viral_df[~viral_df['is_contam']].filter(['sample', 'poly_group', 'read_count']).rename(
{'read_count': 'reads'}, axis = 1)
viral_decontam.to_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/viral_decontam.tsv',
                      sep='\t', index = False)

viral_contamination =  viral_df[viral_df['is_contam']].filter(['sample', 'poly_group', 'read_count']).rename(
{'read_count': 'reads'}, axis = 1)
viral_contamination.to_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/viral_contamination.tsv',
                           sep='\t', index = False)

In [310]:
viral_contamination.groupby('poly_group').sum()

                                   sample  reads
poly_group
194.0       SEZONOWISLIZARD001_S36_657719    277

In [312]:
contig_calls_no_hex = contig_calls[(contig_calls['chordata'] != True) | (contig_calls['curated'])]

# Reset index
contig_calls_no_hex = contig_calls_no_hex.reset_index().drop('index', axis = 1)

In [317]:
all_decontam = decontam(sum_over(contig_calls_no_hex, 'taxid'), 'taxid', 0.0000001)

In [319]:
lca_df = contig_calls_no_hex[~contig_calls_no_hex['curated']]
lca_df = lca_df[~lca_df['sample'].str.contains('ater')]
lca_df = (sum_over(lca_df, 'taxid')
                          .merge(all_decontam.filter(['sample', 'taxid', 'is_contam']),
                                                                      on = ['sample', 'taxid'],
                                                                      how = 'left'))

In [321]:
lca_df.groupby('is_contam')['read_count'].sum()

is_contam
False    77880961
True     27170946
Name: read_count, dtype: int64

In [327]:
# Convert is_contam to boolean (NaN becomes False)
lca_df['is_contam'] = lca_df['is_contam'].fillna(False).astype(bool)

# Write decontaminated data
lca_decontam = lca_df[~lca_df['is_contam']].filter(['sample', 'taxid', 'read_count']).rename(
    {'read_count': 'reads'}, axis=1)
lca_decontam.to_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/lca_decontam.tsv',
                    sep='\t', index=False)

# Write contamination data
lca_contamination = lca_df[lca_df['is_contam']].filter(['sample', 'taxid', 'read_count']).rename(
    {'read_count': 'reads'}, axis=1)
lca_contamination.to_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/lca_contamination.tsv',
                         sep='\t', index=False)

/var/folders/xt/vz8fznds4hdbfcxyds95mtp00000gp/T/ipykernel_80064/2986126574.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lca_df['is_contam'] = lca_df['is_contam'].fillna(False).astype(bool)

In [125]:

read_counts = sum_over(contig_calls, 'poly_group')

/var/folders/xt/vz8fznds4hdbfcxyds95mtp00000gp/T/ipykernel_18590/2757719873.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  return df[[category, "contig_name", 'sample', 'read_count']].groupby([category, 'sample']).sum().reset_index()

In [329]:
lca_contamination.groupby('taxid').sum()

                                                      sample   reads
taxid
78.0       AIAMAR010_LIV_S30_663038AIAMA_GOT007_OS_S45_67...      61
266.0      AIAMAPIG002_S64_657714AIMGLDOG001_S59_657733OD...      55
287.0      AIAMADOG001_S40_657732AIAMADOG002_OS_S64_67346...  126401
293.0      AIAMAGOAT001_S48_656109AIAMASHEEP001_S53_65607...     106
294.0      AIAMAGOAT001_S48_656109AIAMAGOAT003_S50_657720...    3501
...                                                      ...     ...
3063997.0                            AIAMAGOAT001_S48_656109      18
3068314.0  AIAMADOG002_OS_S64_673467AIAMAR014_LIV_S34_663...      14
3078265.0                             AIMGLDOG001_S59_657733       9
3121370.0                             AIMGLDOG001_S59_657733       4
3121376.0  AIAMA_SHP006_OS_S48_673466AIMGLDOG001_S59_6577...      29

[502 rows x 2 columns]

In [331]:
viral_contam_idx = (contig_calls_no_hex.merge(viral_df[['sample', 'poly_group', 'is_contam']],
                          on = ['sample', 'poly_group'], how = 'left')['is_contam'] == True)

In [333]:
lca_contam_loaded = contig_calls_no_hex.merge(lca_df[['sample', 'taxid', 'is_contam']],
                          on = ['sample', 'taxid'], how = 'left')

lca_contam_idx = (lca_contam_loaded['is_contam'] == True) & (lca_contam_loaded['curated'] == False)

In [335]:
not_contam_idx = ~(viral_contam_idx | lca_contam_idx)

In [337]:
contig_calls_decontam = contig_calls_no_hex.loc[~(viral_contam_idx | lca_contam_idx)]

In [341]:
contig_calls_decontam = contig_calls_decontam[
    ~contig_calls_decontam['sample'].str.startswith(('SSP_', 'NTC_', 'NE_'))]

In [343]:
contig_calls_decontam.to_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_calls_decontam.tsv',
                             sep='\t', index = False)

In [345]:
contig_calls.groupby('taxon_group')['read_count'].sum()

taxon_group
Ambiguous      201297
Archaea        251902
Bacteria     77399808
Eukaryota    15568414
Metazoa       4373277
Viruses      62533121
chordata     29165141
Name: read_count, dtype: int64

In [347]:
contig_calls_decontam.groupby('taxon_group')['read_count'].sum()

taxon_group
Ambiguous      100674
Archaea        251902
Bacteria     57574440
Eukaryota     8832705
Metazoa       3815190
Viruses      62528978
Name: read_count, dtype: int64

In [349]:
contig_calls_no_hex.loc[(viral_contam_idx | lca_contam_idx)].groupby('taxon_group')['read_count'].sum()

taxon_group
Ambiguous       98245
Bacteria     19783605
Eukaryota     6727905
Metazoa        557896
Viruses          3572
Name: read_count, dtype: int64

In [351]:
from ete3 import NCBITaxa
ncbi = NCBITaxa()
def taxid2name(taxid):
    return ncbi.get_taxid_translator([taxid])[taxid]

In [353]:
contig_calls_decontam = pd.read_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_calls_decontam.tsv',
                                    sep='\t')

/var/folders/xt/vz8fznds4hdbfcxyds95mtp00000gp/T/ipykernel_80064/2487686838.py:1: DtypeWarning: Columns (4,16,19) have mixed types. Specify dtype option on import or set low_memory=False.
  contig_calls_decontam = pd.read_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_calls_decontam.tsv',

In [355]:
contig_calls_decontam.head()

,sample,contig_name,contig_length,read_count,nr,nt_or_nr,bitscore,align_length,taxon_group_blast,tax_id,...,cluster,taxid_curated,poly_group,name,provisional_name,segment,curated,rdrp,taxon_group,taxid
0,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1021_length_47...,477,13,True,nr,136.0,111.0,Viruses,11855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,Viruses,11855.0
1,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1095_length_46...,467,35,True,nr,170.0,135.0,Viruses,11855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,Viruses,11855.0
2,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1468_length_42...,429,94,True,nr,109.0,108.0,Viruses,2913605.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,Viruses,2913605.0
3,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1577_length_42...,421,17,True,nr,120.0,76.0,Viruses,11855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,Viruses,11855.0
4,AIAMAAGR001_LIV_S46_662105,AIAMAAGR001_LIV_S46_662105_NODE_1801_length_40...,405,9,True,nr,114.0,92.0,Bacteria,2849492.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,Bacteria,2849492.0

In [402]:
# Updated partition list to include mammals
partition = "Apicomplexa Crithidia Pecora Carnivora Homininae Rodentia Leporidae Aves Platyhelminthes Nematoda Fungi Mammalia".split()

# Get name translator for the updated partition
partition = ncbi.get_name_translator(partition)

# Reverse the dictionary for quick lookup
partition = {v[0]: k for k, v in partition.items()}

def get_category(taxid):
    if not taxid:
        return None
    try:
        lineage = ncbi.get_lineage(taxid)
    except:
        return 'NA'
    for k in partition:
        if k in lineage:
            return partition[k]
    else:
        return 'NA'

In [404]:
partition

{5794: 'Apicomplexa',
 8782: 'Aves',
 33554: 'Carnivora',
 5655: 'Crithidia',
 4751: 'Fungi',
 207598: 'Homininae',
 9979: 'Leporidae',
 40674: 'Mammalia',
 6231: 'Nematoda',
 35500: 'Pecora',
 6157: 'Platyhelminthes',
 9989: 'Rodentia'}

In [406]:
category = contig_calls_decontam['taxid'].apply(get_category)
contig_calls_decontam['category'] = category

/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 85948 was translated into 147567
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2991674 was translated into 3383038
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 7604 was translated into 133437
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2052317 was translated into 3107663
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1914757 was translated into 1768011
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2789583 was translated into 2841044
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2991676 was translated into 3383035
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2650730 was translated into 261694
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1906744 was translated into 1796644
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2817377 was translated into 2817376
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 139420 was translated into 2498619
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2811023 was translated into 1903157
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 436010 was translated into 1759441
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1114980 was translated into 2144
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 686832 was translated into 76867
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))

In [408]:
contig_calls_decontam[['category', 'read_count']].groupby('category').sum()

                 read_count
category
Apicomplexa           89346
Fungi               2554965
Mammalia                 23
NA                127586437
Nematoda            2826905
Platyhelminthes       46213

In [410]:
lca = pd.read_csv('/Volumes/aine_store/SENZOR_project/SPlited_SENSOR_porject/IDseq/Combined_SENZOR_results/contig_stats_lca_annotated.tsv', sep='\t')
category = lca['tax_id'].apply(get_category)
lca['category'] = category
lca[['category', 'read_count']].groupby('category').sum()

/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 59451 was translated into 3371016
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 143291 was translated into 132908
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 85948 was translated into 147567
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 90247 was translated into 3371155
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 228257 was translated into 3082113
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2991674 was translated into 3383038
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 7604 was translated into 133437
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2052317 was translated into 3107663
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1914757 was translated into 1768011
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2789583 was translated into 2841044
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2991676 was translated into 3383035
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 39086 was translated into 3370998
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2650730 was translated into 261694
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1906744 was translated into 1796644
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2817377 was translated into 2817376
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 139420 was translated into 2498619
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2811023 was translated into 1903157
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 436010 was translated into 1759441
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 77222 was translated into 3370833
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 381198 was translated into 8845
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1114980 was translated into 2144
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 9413 was translated into 3371112
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 59452 was translated into 3371021
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 302711 was translated into 225400
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/ifeanyi/anaconda3/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 686832 was translated into 76867
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))

                 read_count
category
Apicomplexa           89346
Aves                2858597
Carnivora            792210
Fungi               2840633
Homininae             31620
Leporidae             25769
Mammalia           25322116
NA                109080289
Nematoda            3141235
Platyhelminthes       46213

In [388]:
apicomplexa = contig_calls_decontam[contig_calls_decontam['category'] == 'Apicomplexa'].copy()

In [390]:
apicomplexa['name'] = apicomplexa['tax_id'].apply(taxid2name)

In [392]:
apicomplexa.groupby(['sample', 'name'])['read_count'].sum()

sample                         name
AIAMADOG001_S40_657732         Plasmodium vivax North Korean       7
AIAMADOG002_OS_S64_673467      Cryptosporidium canis               4
AIAMAGOAT001_S48_656109        Babesia bigemina                   48
                               Babesia ovata                     243
AIAMAGOAT002_S49_656110        Babesia bovis T2Bo                  6
                                                                ...
SEZONOWOGGOAT018_S66_1_657730  Babesia bigemina                 2279
                               Babesia ovata                     155
                               Sarcocystis neurona                 7
SEZONOWOGR002_LIV_S48_666373   Plasmodium berghei                 24
SEZONOWOGR003_LIV_S49_666374   Plasmodium yoelii yoelii           35
Name: read_count, Length: 243, dtype: int64

In [394]:
platy=contig_calls_decontam[contig_calls_decontam['category'] == 'Platyhelminthes'].copy()

In [396]:
platy['name'] = platy['tax_id'].apply(taxid2name)

In [400]:
platy.groupby(['sample', 'name'])['read_count'].sum()

sample                         name
AIAMAAGR001_LIV_S46_662105     Clonorchis sinensis                2427
AIAMAGOAT002_S49_656110        Fasciola hepatica                     6
                               Heterobilharzia americana             6
                               Macrostomum lignano                  24
                               Paragonimus skrjabini miyazakii      14
                                                                  ...
SEZONOWISGOAT013_S24_2_657729  Schistosoma mansoni                  10
SEZONOWOGDOG014_S21_657751     Paragonimus westermani              149
SEZONOWOGDOG017_S22_657753     Taenia asiatica                      19
SEZONOWOGR002_LIV_S48_666373   Echinococcus granulosus              12
SEZONOWOGR003_LIV_S49_666374   Echinococcus granulosus              21
Name: read_count, Length: 171, dtype: int64